apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service-clusterip.yaml

configMapGenerator:
  - name: payment-config
    files:
      - application.yaml
    options:
      labels:
        app: payment-service